### ISSUE TITLE
Run the Servers Locally

### ISSUE THREAD

**Issue by duttojar** [duttojar/flex-gaming#8]
- Ask Jonathan for access
- Ask how is the website hosted
- Clone repo onto laptop
- Get website on laptop
- Send requests to the API

**Comment by 037Leo0101** [comment]
Got it to run on Mac locally, haven't sent request to the API yet

**Comment by mach7839coloradoedu** [comment]
I got it to run on Windows locally, but sending a request to the API does not seem to work.
